spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  #MCP
  ai:
    mcp:
      server:
        name: productMcp
        version: 0.1.1
        protocol: streamable
        stdio: false
        type: sync

management:
  endpoints:
    web:
      exposure:
        include: "*"


server:
  port: 8081

app:
  message: "Hello Product!"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true